### ISSUE TITLE
ValueError: Input contains NaN, infinity or a value too large for dtype('float64')

### ISSUE THREAD

**Issue by xiebb123456** [oscar-franzen/alona#1]
Hi,

alona seems a very good tool to do scRNA-analysis, when I run the GSM3689776 data, there ia a problem in the qc step, the output info is :

INFO     3,013 columns detected.
INFO     28,692 genes detected
INFO     224 gene(s) were not mappable.
INFO     These have been written to unmappable.txt
INFO     Current dimensions: (28468, 3013)
INFO     detected and removed 13 mitochondrial gene(s)
INFO     Keeping 2961 out of 3013 cells
INFO     Removing 15,314 genes.
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/miniconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/x/alona/alona/__main__.py", line 7, in <module>
    main()
  File "/home/x/alona/alona/__main__.py", line 4, in main
    run(prog_name='alona.py')
  File "/opt/miniconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/miniconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/miniconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/miniconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/x/alona/alona/alona.py", line 218, in run
    alonacell.load_data()
  File "/home/x/alona/alona/cell.py", line 424, in load_data
    self.find_low_quality_cells()
  File "/home/x/alona/alona/cell.py", line 334, in find_low_quality_cells
    robust_cov = MinCovDet(random_state=seed).fit(qc_mat)
  File "/opt/miniconda3/lib/python3.7/site-packages/sklearn/covariance/robust_covariance.py", line 639, in fit
    X = check_array(X, ensure_min_samples=2, estimator='MinCovDet')
  File "/opt/miniconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 542, in check_array
    allow_nan=force_all_finite == 'allow-nan')
  File "/opt/miniconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 56, in _assert_all_finite
    raise ValueError(msg_err.format(type_err, X.dtype))
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

**Comment by oscar-franzen** [comment]
**I have fixed it and pushed the edit.** It was caused by find_low_quality_cells() and mismatches in a list due to some cells were cleared out earlier by simple filters.
